name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python version
      run: python --version
    - name: Instalar dependencias
      run: pip install -r requirements.txt
    - name: Entrenar modelo de Machine Learning
      run: python model/train.py
      

